apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwer
  template:
    metadata:
      labels:
        app: qwer
    spec:
      containers:
      - image: okteto.dev/qwer:latest
        name: qwer
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "ee67f707-5dad-417b-84ce-a73ab7219cc5"
        - name: Vless_Path
          value: "/vl554er5"
        - name: Vmess_UUID
          value: "ee67f707-5dad-417b-84ce-a73ab7219cc5"
        - name: Vmess_Path
          value: "/vm62w34d66"
        - name: Share_Path
          value: "/v2link"
